"""Train and compare the supervised and unsupervised detectors.

Supervised:   Decision Tree, trained on labelled normal + attack rows.
Unsupervised: K-Means, trained on NORMAL ROWS ONLY. A new flow is scored by its
              distance to the nearest cluster centre; beyond a threshold it is
              flagged anomalous.

Methodology note that matters for the write-up: the K-Means threshold is taken
from a percentile of the distances of the *normal training data*. It never sees
an attack row. If the threshold were tuned on data containing attacks the model
would be quietly supervised, and the whole comparison would be invalid.

Both models are exported to C++ headers so the simulator runs the exact same
decision logic that was evaluated here.

Usage:
    python train.py --train ../data/flows_sim.csv
    python train.py --train ../data/flows_sim.csv --test ../data/flows_lowrate.csv
"""
import argparse
import json
import os

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier

from schema import FEATURES, LABEL

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, "..", "src")
RESULTS_DIR = os.path.join(HERE, "..", "results")


# ----------------------------------------------------------------- metrics

def metrics(y_true, y_pred):
    y_true = np.asarray(y_true).astype(int)
    y_pred = np.asarray(y_pred).astype(int)
    tp = int(((y_true == 1) & (y_pred == 1)).sum())
    tn = int(((y_true == 0) & (y_pred == 0)).sum())
    fp = int(((y_true == 0) & (y_pred == 1)).sum())
    fn = int(((y_true == 1) & (y_pred == 0)).sum())
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    f1 = 2 * prec * rec / (prec + rec) if prec + rec else 0.0
    return {
        "accuracy": (tp + tn) / max(1, len(y_true)),
        "precision": prec,
        "recall": rec,
        "f1": f1,
        "fpr": fp / (fp + tn) if fp + tn else 0.0,
        "tp": tp, "tn": tn, "fp": fp, "fn": fn,
    }


def print_table(results):
    cols = ["accuracy", "precision", "recall", "f1", "fpr"]
    name_w = max(len(n) for n in results) + 2
    print("\n" + " " * name_w + "".join(f"{c:>11}" for c in cols))
    print("-" * (name_w + 11 * len(cols)))
    for name, m in results.items():
        print(f"{name:<{name_w}}" + "".join(f"{m[c]:>11.4f}" for c in cols))
    print()
    for name, m in results.items():
        print(f"  {name}: TP={m['tp']} TN={m['tn']} FP={m['fp']} FN={m['fn']}")


# ------------------------------------------------------------ K-Means model

class KMeansDetector:
    """Distance-to-nearest-centroid anomaly detector, fit on normal traffic."""

    def __init__(self, k=4, percentile=99.0, seed=0):
        self.k = k
        self.percentile = percentile
        self.seed = seed

    def fit(self, X_normal):
        self.scaler = StandardScaler().fit(X_normal)
        Xs = self.scaler.transform(X_normal)
        self.km = KMeans(n_clusters=self.k, n_init=10,
                         random_state=self.seed).fit(Xs)
        d = self._dist(Xs)
        # Threshold from normal data only - no attack row is involved.
        self.threshold = float(np.percentile(d, self.percentile))
        return self

    def _dist(self, Xs):
        return np.linalg.norm(
            Xs[:, None, :] - self.km.cluster_centers_[None, :, :], axis=2
        ).min(axis=1)

    def predict(self, X):
        return (self._dist(self.scaler.transform(X)) > self.threshold).astype(int)

    def score(self, X):
        return self._dist(self.scaler.transform(X))


# ------------------------------------------------------------- C++ export

def export_decision_tree(clf, path):
    t = clf.tree_
    lines = []

    def rec(node, depth):
        pad = "    " * depth
        if t.children_left[node] == -1:
            cls = int(clf.classes_[int(np.argmax(t.value[node][0]))])
            lines.append(f"{pad}return {cls};")
        else:
            fi = int(t.feature[node])
            lines.append(f"{pad}if (f[{fi}] <= {t.threshold[node]:.6f}) "
                         f"{{ // {FEATURES[fi]}")
            rec(int(t.children_left[node]), depth + 1)
            lines.append(f"{pad}}} else {{")
            rec(int(t.children_right[node]), depth + 1)
            lines.append(f"{pad}}}")

    rec(0, 1)
    body = "\n".join(lines)
    feat_doc = "\n".join(f"//   f[{i}] = {n}" for i, n in enumerate(FEATURES))
    with open(path, "w") as fh:
        fh.write(f"""// AUTO-GENERATED by ml/train.py - do not edit by hand.
// Decision Tree (supervised). Returns 1 for attack, 0 for normal.
//
// Feature vector layout:
{feat_doc}
#ifndef DECISION_TREE_H_
#define DECISION_TREE_H_

inline int dtClassify(const double f[{len(FEATURES)}])
{{
{body}
}}

#endif
""")


def export_kmeans(det, path):
    def arr(v):
        return ", ".join(f"{x:.6f}" for x in v)

    centroids = ",\n    ".join(
        "{" + arr(c) + "}" for c in det.km.cluster_centers_)
    with open(path, "w") as fh:
        fh.write(f"""// AUTO-GENERATED by ml/train.py - do not edit by hand.
// K-Means anomaly detector (unsupervised). Returns 1 for anomaly, 0 for normal.
// Trained on NORMAL traffic only; threshold is the {det.percentile:g}th percentile
// of normal training distances.
#ifndef KMEANS_MODEL_H_
#define KMEANS_MODEL_H_

#include <cmath>

namespace kmeans {{

const int   NUM_FEATURES = {len(FEATURES)};
const int   NUM_CLUSTERS = {det.k};
const double THRESHOLD   = {det.threshold:.6f};

const double MEAN[{len(FEATURES)}]  = {{{arr(det.scaler.mean_)}}};
const double SCALE[{len(FEATURES)}] = {{{arr(det.scaler.scale_)}}};

const double CENTROIDS[{det.k}][{len(FEATURES)}] = {{
    {centroids}
}};

}} // namespace kmeans

// Distance from the flow to its nearest normal cluster centre.
inline double kmDistance(const double f[{len(FEATURES)}])
{{
    double best = -1.0;
    for (int c = 0; c < kmeans::NUM_CLUSTERS; c++) {{
        double sum = 0.0;
        for (int i = 0; i < kmeans::NUM_FEATURES; i++) {{
            double z = (f[i] - kmeans::MEAN[i]) / kmeans::SCALE[i];
            double d = z - kmeans::CENTROIDS[c][i];
            sum += d * d;
        }}
        double dist = std::sqrt(sum);
        if (best < 0.0 || dist < best) best = dist;
    }}
    return best;
}}

inline int kmClassify(const double f[{len(FEATURES)}])
{{
    return kmDistance(f) > kmeans::THRESHOLD ? 1 : 0;
}}

#endif
""")


# ------------------------------------------------------------------- main

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--train", required=True)
    ap.add_argument("--test", default=None,
                    help="optional separate test set, e.g. an attack intensity "
                         "never seen during training")
    ap.add_argument("--k", type=int, default=4)
    ap.add_argument("--percentile", type=float, default=99.0)
    ap.add_argument("--max-depth", type=int, default=8)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    df = pd.read_csv(args.train)
    X, y = df[FEATURES].to_numpy(float), df[LABEL].to_numpy(int)

    X_tr, X_te, y_tr, y_te = train_test_split(
        X, y, test_size=0.25, random_state=args.seed, stratify=y)

    dt = DecisionTreeClassifier(max_depth=args.max_depth,
                                random_state=args.seed).fit(X_tr, y_tr)

    km = KMeansDetector(k=args.k, percentile=args.percentile,
                        seed=args.seed).fit(X_tr[y_tr == 0])

    print(f"train rows={len(X_tr)} (normal={int((y_tr==0).sum())}, "
          f"attack={int((y_tr==1).sum())})   held-out rows={len(X_te)}")
    print(f"K-Means: k={args.k}, threshold={km.threshold:.4f} "
          f"({args.percentile:g}th pct of normal distances)")

    results = {
        "Decision Tree (supervised)": metrics(y_te, dt.predict(X_te)),
        "K-Means (unsupervised)": metrics(y_te, km.predict(X_te)),
    }
    print("\n=== Held-out test set (same distribution as training) ===")
    print_table(results)

    all_results = {"seen": results}

    if args.test:
        dft = pd.read_csv(args.test)
        Xt, yt = dft[FEATURES].to_numpy(float), dft[LABEL].to_numpy(int)
        unseen = {
            "Decision Tree (supervised)": metrics(yt, dt.predict(Xt)),
            "K-Means (unsupervised)": metrics(yt, km.predict(Xt)),
        }
        print(f"=== Unseen attack pattern: {os.path.basename(args.test)} ===")
        print_table(unseen)
        all_results["unseen"] = unseen

    print("Decision Tree feature importance:")
    for n, imp in sorted(zip(FEATURES, dt.feature_importances_),
                         key=lambda p: -p[1]):
        print(f"  {n:<16} {imp:.4f}")

    os.makedirs(SRC_DIR, exist_ok=True)
    os.makedirs(RESULTS_DIR, exist_ok=True)
    export_decision_tree(dt, os.path.join(SRC_DIR, "DecisionTree.h"))
    export_kmeans(km, os.path.join(SRC_DIR, "KMeansModel.h"))
    with open(os.path.join(RESULTS_DIR, "ml_metrics.json"), "w") as fh:
        json.dump(all_results, fh, indent=2)

    print("\nexported -> src/DecisionTree.h, src/KMeansModel.h")
    print("exported -> results/ml_metrics.json")


if __name__ == "__main__":
    main()
