#ifndef SDNDDOS_DDOSDETECTORAPP_H_
#define SDNDDOS_DDOSDETECTORAPP_H_

#include <fstream>
#include <set>
#include <string>

#include <omnetpp.h>

#include "openflow/controllerApps/AbstractControllerApp.h"

namespace sdnddos {

class DDoSFlowStats;

/**
 * Controller application that turns flow statistics into blocking decisions.
 *
 * Runs in one of three modes, set from the ini file:
 *
 *   collect  - label rows from ground truth and write the training CSV.
 *              No blocking. This is how the dataset is produced.
 *   dt       - classify with the exported Decision Tree (supervised).
 *   kmeans   - classify with the exported K-Means detector (unsupervised).
 *
 * The two detection modes run the exact decision logic that was evaluated
 * offline in Python, because both headers are generated by ml/train.py rather
 * than reimplemented by hand.
 */
class DDoSDetectorApp : public openflow::AbstractControllerApp
{
  public:
    virtual ~DDoSDetectorApp();

  protected:
    enum Mode { MODE_COLLECT, MODE_DT, MODE_KMEANS };

    Mode mode = MODE_COLLECT;
    double blockDuration = 10.0;
    bool writeCsv = false;
    std::string csvPath;
    std::ofstream csv;

    /**
     * Ground truth, used only for labelling in collect mode and for scoring.
     * The classifiers never see it.
     */
    std::set<uint32_t> attackerIps;
    bool attackersResolved = false;

    long rowsWritten = 0;
    long flowsSeen = 0;
    long detections = 0;
    long blocksIssued = 0;
    long truePos = 0, falsePos = 0, trueNeg = 0, falseNeg = 0;
    omnetpp::simtime_t firstAttackFlowSeen = -1;
    omnetpp::simtime_t firstDetection = -1;      // any detection, true or false
    omnetpp::simtime_t firstTrueDetection = -1;  // first correct one
    long falsePositivesBeforeAttack = 0;

    virtual void initialize() override;
    virtual void receiveSignal(omnetpp::cComponent *src, omnetpp::simsignal_t id,
                               omnetpp::cObject *obj, omnetpp::cObject *details) override;
    virtual void finish() override;

    void handleFlowStats(DDoSFlowStats *stats);
    void sendBlock(uint32_t inPort, uint32_t srcIp, omnetpp::cMessage *context);
    void resolveAttackers();
};

} // namespace sdnddos

#endif
