// AUTO-GENERATED by ml/train.py - do not edit by hand.
// Decision Tree (supervised). Returns 1 for attack, 0 for normal.
//
// Feature vector layout:
//   f[0] = pkt_rate
//   f[1] = byte_rate
//   f[2] = avg_pkt_size
//   f[3] = duration
//   f[4] = pair_flow
//   f[5] = port_src_count
#ifndef DECISION_TREE_H_
#define DECISION_TREE_H_

inline int dtClassify(const double f[6])
{
    if (f[1] <= 116465.500000) { // byte_rate
        return 0;
    } else {
        return 1;
    }
}

#endif
