// AUTO-GENERATED by ml/train.py - do not edit by hand.
// K-Means anomaly detector (unsupervised). Returns 1 for anomaly, 0 for normal.
// Trained on NORMAL traffic only; threshold is the 99th percentile
// of normal training distances.
#ifndef KMEANS_MODEL_H_
#define KMEANS_MODEL_H_

#include <cmath>

namespace kmeans {

const int   NUM_FEATURES = 6;
const int   NUM_CLUSTERS = 3;
const double THRESHOLD   = 2.053589;

const double MEAN[6]  = {14.089918, 7429.062670, 447.907357, 27.521115, 0.673025, 2.032698};
const double SCALE[6] = {8.666078, 5064.897645, 140.732464, 16.123446, 0.469108, 1.320152};

const double CENTROIDS[3][6] = {
    {0.628490, 0.639271, 0.697015, -0.153162, 0.697015, -0.675735},
    {-1.315272, -1.336041, -1.434689, -0.008525, -1.434689, 0.404476},
    {0.675685, 0.683361, 0.697015, 0.553277, 0.697015, 1.476437}
};

} // namespace kmeans

// Distance from the flow to its nearest normal cluster centre.
inline double kmDistance(const double f[6])
{
    double best = -1.0;
    for (int c = 0; c < kmeans::NUM_CLUSTERS; c++) {
        double sum = 0.0;
        for (int i = 0; i < kmeans::NUM_FEATURES; i++) {
            double z = (f[i] - kmeans::MEAN[i]) / kmeans::SCALE[i];
            double d = z - kmeans::CENTROIDS[c][i];
            sum += d * d;
        }
        double dist = std::sqrt(sum);
        if (best < 0.0 || dist < best) best = dist;
    }
    return best;
}

inline int kmClassify(const double f[6])
{
    return kmDistance(f) > kmeans::THRESHOLD ? 1 : 0;
}

#endif
